//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneNorth.ExpressSubitem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prototypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prototypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneNorth.ExpressSubitem.Prototypes", typeof(Prototypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;add-new-item&quot;&gt;
        ///    &lt;div class=&quot;scContentButtons&quot;&gt;
        ///        &lt;a class=&quot;scContentButton&quot; onclick=&quot;javascript:return ExpressSubitem_AddNewItem(event,&apos;{0}&apos;)&quot; href=&quot;#&quot;&gt;Add New&lt;/a&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string AddExpressSubitem {
            get {
                return ResourceManager.GetString("AddExpressSubitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;checkbox field-container&quot; fieldId=&quot;{1}&quot;&gt;
        ///    &lt;table class=&quot;scEditorFieldMarker&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; border=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;field-marker scEditorFieldMarkerBarCell&quot;&gt;&lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4px&quot; height=&quot;1px&quot;&gt;&lt;/td&gt;
        ///            &lt;td class=&quot;scEditorFieldMarkerInputCell&quot;&gt;
        ///                &lt;div style=&quot;&quot; class=&quot;scCheckBox&quot;&gt;
        ///                    &lt;input class=&quot;scContentControlCheckbox&quot; type=&quot;checkbox&quot; name=&quot;{1}&quot; value=&quot;1&quot; {2} {3} &gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Checkbox {
            get {
                return ResourceManager.GetString("Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;datetime field-container&quot; fieldId=&quot;{3}&quot;&gt;
        ///    &lt;table class=&quot;scEditorFieldMarker&quot; border=&quot;0&quot; cellPadding=&quot;0&quot; cellSpacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;field-marker scEditorFieldMarkerBarCell&quot;&gt;&lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot;/&gt;&lt;/td&gt;
        ///            &lt;td class=&quot;scEditorFieldMarkerInputCell&quot;&gt;
        ///                {4}
        ///                &lt;div class=&quot;scEditorFieldLabel&quot;&gt;{0}: {5}&lt;/div&gt;
        ///                &lt;div class=&quot;scDateTimePickerContainer&quot;&gt;
        ///                    {1}
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;dropdown field-container&quot; fieldId=&quot;{1}&quot;&gt;
        ///    &lt;table class=&quot;scEditorFieldMarker&quot; border=&quot;0&quot; cellPadding=&quot;0&quot; cellSpacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;field-marker scEditorFieldMarkerBarCell&quot;&gt;&lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot;/&gt;&lt;/td&gt;
        ///            &lt;td class=&quot;scEditorFieldMarkerInputCell&quot;&gt;
        ///                &lt;div class=&quot;scEditorFieldLabel&quot;&gt;{0}: {5}&lt;/div&gt;
        ///                &lt;select class=&quot;scContentControl&quot; name=&quot;{1}&quot; {3}&gt;
        ///                    {2}
        ///                &lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dropdown {
            get {
                return ResourceManager.GetString("Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;sub-item{2}&quot; id=&quot;ExpressSubitem_{0:N}&quot; itemid=&quot;{0}&quot; isnew=&quot;{4}&quot; version=&quot;{5}&quot;&gt;
        ///    &lt;table style=&quot;width:100%;&quot; ondblclick=&quot;javascript:return ExpressSubitem_doubleClick(event);&quot; class=&quot;no-select&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:100%;&quot;&gt;
        ///                &lt;div class=&quot;sub-item-header&quot;&gt;
        ///                    &lt;div class=&quot;sub-item-validation&quot;&gt;
        ///                        &lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot; /&gt;&lt;/div&gt;
        ///                    &lt;div class=&quot;title&quot;&gt;{1}&lt;/div&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemRow {
            get {
                return ResourceManager.GetString("ItemRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;sub-item{2}&quot; id=&quot;ExpressSubitem_{0:N}&quot; itemid=&quot;{0}&quot; isnew=&quot;{4}&quot; version=&quot;{5}&quot;&gt;
        ///    &lt;table style=&quot;width:100%;&quot; ondblclick=&quot;javascript:return ExpressSubitem_doubleClick(event);&quot; class=&quot;no-select&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td style=&quot;width:100%;&quot;&gt;
        ///                &lt;div class=&quot;sub-item-header&quot;&gt;
        ///                    &lt;div class=&quot;sub-item-validation&quot;&gt;
        ///                        &lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot; /&gt;&lt;/div&gt;
        ///                    &lt;div class=&quot;title&quot;&gt;{1}&lt;/div&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemRowDisabled {
            get {
                return ResourceManager.GetString("ItemRowDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;richtext field-container&quot; rtControlId=&quot;{2}&quot; fieldId=&quot;{3}&quot;&gt;
        ///    &lt;table class=&quot;scEditorFieldMarker&quot; border=&quot;0&quot; cellPadding=&quot;0&quot; cellSpacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;field-marker scEditorFieldMarkerBarCell&quot;&gt;&lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot;/&gt;&lt;/td&gt;
        ///            &lt;td class=&quot;scEditorFieldMarkerInputCell&quot;&gt;
        ///                {4}
        ///                &lt;div class=&quot;scEditorFieldLabel&quot;&gt;{0}: {5}&lt;/div&gt;
        ///                &lt;div class=&quot;defaultFieldEditorsFrameContainer&quot; style=&quot;o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RichText {
            get {
                return ResourceManager.GetString("RichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;{5} field-container&quot; fieldId=&quot;{3}&quot;&gt;
        ///    &lt;table class=&quot;scEditorFieldMarker&quot; border=&quot;0&quot; cellPadding=&quot;0&quot; cellSpacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;field-marker scEditorFieldMarkerBarCell&quot;&gt;&lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot;/&gt;&lt;/td&gt;
        ///            &lt;td class=&quot;scEditorFieldMarkerInputCell&quot;&gt;
        ///                {4}
        ///                &lt;div class=&quot;scEditorFieldLabel&quot;&gt;{0}: {6}&lt;/div&gt;
        ///                &lt;div&gt;
        ///                    {1}
        ///                &lt;/div&gt;
        ///            &lt;/td&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StandardWrapper {
            get {
                return ResourceManager.GetString("StandardWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;textbox field-container&quot; fieldId=&quot;{1}&quot;&gt;
        ///    &lt;table class=&quot;scEditorFieldMarker&quot; border=&quot;0&quot; cellPadding=&quot;0&quot; cellSpacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;field-marker scEditorFieldMarkerBarCell&quot;&gt;&lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot;/&gt;&lt;/td&gt;
        ///            &lt;td class=&quot;scEditorFieldMarkerInputCell&quot;&gt;
        ///                &lt;div class=&quot;scEditorFieldLabel&quot;&gt;{0}: {4}&lt;/div&gt;
        ///                &lt;input class=&quot;scContentControl&quot; type=&quot;text&quot; name=&quot;{1}&quot; value=&quot;{2}&quot; {3} /&gt;
        ///            &lt;/td&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;tree field-container&quot; fieldId=&quot;{3}&quot; sourceId=&quot;{4}&quot;&gt;
        ///    &lt;table class=&quot;scEditorFieldMarker&quot; border=&quot;0&quot; cellPadding=&quot;0&quot; cellSpacing=&quot;0&quot;&gt;
        ///        &lt;tr&gt;
        ///            &lt;td class=&quot;field-marker scEditorFieldMarkerBarCell&quot;&gt;&lt;img src=&quot;/sitecore/images/blank.gif&quot; width=&quot;4&quot; height=&quot;1&quot;/&gt;&lt;/td&gt;
        ///            &lt;td class=&quot;scEditorFieldMarkerInputCell&quot;&gt;
        ///                &lt;div class=&quot;scEditorFieldLabel&quot;&gt;{0}: {5}&lt;/div&gt;
        ///                &lt;div&gt;
        ///                    {1}
        ///                &lt;/div&gt;
        ///            &lt;/td&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tree {
            get {
                return ResourceManager.GetString("Tree", resourceCulture);
            }
        }
    }
}
